### ISSUE TITLE
Postman window not opening

### ISSUE THREAD

**Issue by trazek** [dnbard/brackets-postman#2]
Hello,

I am running Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97). When I click on the extension icon, the postman window does not come up. I checked the demo and it just shows the postman window already open. Did I miss a menu item or something?

Thanks!

**Comment by oleksbard** [comment]
Extension Icon should open the window. Any errors in Dev Console (`F12` hotkey)?

**Comment by trazek** [comment]
Ah sorry I didn't check that before. The error I am getting is:

"Uncaught TypeError: Cannot read property 'ownerDocument' of null"

thirdparty.min.js is the file complaining about the error.

**Comment by dsrw** [comment]
Postman is using `window._` to compile its template, and is depending on a feature that was removed in lodash 3.0. It seems that the template compile breaks if a version of lodash >= 3.0 gets loaded before the Postman window is shown.

PR #3 switches to using the `thirdparty/lodash` module and also builds the template in a manner that works with lodash 2 and 3 (not actually needed until brackets updates thirdparty/lodash).
